# Site settings
title: CDRPRO.RU
email: ""
description:
  ru: "Макросы для CorelDRAW. Бесплатные книги и уроки по CorelDRAW & PHOTO-PAINT. Блог про разработку."
  en: "Macros & tools for CorelDRAW. Free & open source macros."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cdrpro.ru" # the base hostname & protocol for your site
twitter_username: cdrpro_ru
github_username:  cdrpro

include: [
  favicon.ico
]

exclude: [
  gulp,
  node_modules,
  src,
  gulpfile.js,
  package.json,
  README.md
]

permalink: none # /:categories/:title.html

# Collections
collections:
  macros:
    output: true
    permalink: /macros/:path/
  updates:
    output: false

# Paginate
paginate: 10
paginate_path: /posts/page:num/

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  # Do not use `with_toc_data`
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
