# Site settings
title: CDRPRO.RU
email: ""
description:
  ru: "Макросы для CorelDRAW. Бесплатные макросы, книги и уроки по CorelDRAW & PHOTO-PAINT."
  en: "Macros & tools for CorelDRAW. Free & open source macros."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cdrpro.ru" # the base hostname & protocol for your site
twitter_username: SanichKotikov
github_username: cdrpro-macros
github_page_url: cdrpro.github.io

include: [
  favicon.ico
]

exclude: [
  README.md
]

sass:
  sass_dir: _sass
  style: compressed # nested, compact, expanded, compressed

permalink: none # /:categories/:title.html

# Collections
collections:
  macros:
    output: true
    permalink: /macros/:path/

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  # Do not use `with_toc_data`
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
